/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AyoubBani (https://sketchfab.com/AyoubBani)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rocket-b17a0f9f805c4fa7b978829006bbb57f
Title: Rocket
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { a, useSpring } from '@react-spring/three';
import { useFrame } from '@react-three/fiber';

import RocketScene from '../assets/3d/rocket.glb';

const Rocket = (props) => {
  const rocketRef = useRef();
  const { nodes, materials, animations } = useGLTF(RocketScene);
  const { actions } = useAnimations(animations, rocketRef);

  // Rotation animation using react-spring
  const { rotation } = useSpring({
    from: { rotation: [0, 0, 0] },
    to: { rotation: [0, Math.PI * 2, 0] },
    loop: true,
    config: { duration: 5000 }, // Rotate the rocket every 5 seconds
  });

  // Adding a constant spin using useFrame hook
  useFrame(() => {
    rocketRef.current.rotation.y += 0.01; // Modify the axis or speed as needed

  });

  return (
    <a.group {...props} ref={rocketRef} rotation={rotation} > {/* Applying spring rotation */}
      <group scale={0.040}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            geometry={nodes.Cylinder_white_0.geometry}
            material={materials.white}
          />
          <mesh
            geometry={nodes.Cylinder_red_0.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.Cylinder_metal_0.geometry}
            material={materials.metal}
          />
        </group>
        <group position={[20.4434, 20.3398, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            geometry={nodes.Cylinder001_metal_0.geometry}
            material={materials.metal}
          />
          <mesh
            geometry={nodes.Cylinder001_window_glass_0.geometry}
            material={materials.window_glass}
          />
        </group>
        <group position={[0, -41.7474, 0.1456]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            geometry={nodes.Cylinder008_metal_0.geometry}
            material={materials.metal}
          />
          <mesh
            geometry={nodes.Cylinder008_metal_0_1.geometry}
            material={materials.metal}
          />
        </group>
        <group position={[0.1589, -52.2283, 8.5681]} rotation={[-Math.PI / 2, 0, 0]} scale={9.6364}>
          <mesh
            geometry={nodes.Cube002_whiteSmoke_0.geometry}
            material={materials['white.Smoke']}
          />
          <mesh
            geometry={nodes.Cube002_whiteSmoke_0_1.geometry}
            material={materials['white.Smoke']}
          />
          <mesh
            geometry={nodes.Cube002_whiteSmoke_0_2.geometry}
            material={materials['white.Smoke']}
          />
          <mesh
            geometry={nodes.Cube002_whiteSmoke_0_3.geometry}
            material={materials['white.Smoke']}
          />
          <mesh
            geometry={nodes.Cube002_whiteSmoke_0_4.geometry}
            material={materials['white.Smoke']}
          />
          <mesh
            geometry={nodes.Cube002_whiteSmoke_0_5.geometry}
            material={materials['white.Smoke']}
          />
          <mesh
            geometry={nodes.Cube002_whiteSmoke_0_6.geometry}
            material={materials['white.Smoke']}
          />
        </group>
        <group
          position={[0.2195, -51.5489, -7.501]}
          rotation={[-Math.PI / 2, 0, 2.009]}
          scale={8.7247}>
          <mesh
            geometry={nodes.Cube015_whiteSmoke_0.geometry}
            material={materials['white.Smoke']}
          />
          <mesh
            geometry={nodes.Cube015_whiteSmoke_0_1.geometry}
            material={materials['white.Smoke']}
          />
          <mesh
            geometry={nodes.Cube015_whiteSmoke_0_2.geometry}
            material={materials['white.Smoke']}
          />
          <mesh
            geometry={nodes.Cube015_whiteSmoke_0_3.geometry}
            material={materials['white.Smoke']}
          />
          <mesh
            geometry={nodes.Cube015_whiteSmoke_0_4.geometry}
            material={materials['white.Smoke']}
          />
          <mesh
            geometry={nodes.Cube015_whiteSmoke_0_5.geometry}
            material={materials['white.Smoke']}
          />
          <mesh
            geometry={nodes.Cube015_whiteSmoke_0_6.geometry}
            material={materials['white.Smoke']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_metal2_0.geometry}
          material={materials['metal.2']}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003_red_0.geometry}
          material={materials.material}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={98.354}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_metal2_0.geometry}
          material={materials['metal.2']}
          position={[28.9209, 21.844, 0]}
          rotation={[-Math.PI / 2, -0.1745, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_whiteSmoke_0.geometry}
          material={materials['white.Smoke']}
          position={[9.2425, -68.2651, 16.2696]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={3.7794}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_whiteSmoke_0.geometry}
          material={materials['white.Smoke']}
          position={[-6.1085, -63.3659, 1.6018]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={2.8058}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_whiteSmoke_0.geometry}
          material={materials['white.Smoke']}
          position={[8.0366, -71.2579, 9.0534]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={2.61}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_whiteSmoke_0.geometry}
          material={materials['white.Smoke']}
          position={[-1.5801, -74.1228, 13.9248]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.6536}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_whiteSmoke_0.geometry}
          material={materials['white.Smoke']}
          position={[-3.6746, -65.4884, 21.6005]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.6536}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_whiteSmoke_0.geometry}
          material={materials['white.Smoke']}
          position={[2.8531, -60.517, 17.3877]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={2.61}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011_whiteSmoke_0.geometry}
          material={materials['white.Smoke']}
          position={[1.7533, -67.5508, 4.5378]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.9628}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012_whiteSmoke_0.geometry}
          material={materials['white.Smoke']}
          position={[-1.2671, -66.8892, 17.7669]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={2.4237}
        />
      </group>
    </a.group>
  );
};

useGLTF.preload(RocketScene);

export default Rocket;
